# Generated by Django 3.2.13 on 2022-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220424_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequirements',
            name='project_target',
            field=models.ManyToManyField(default='', to='project.TargetAudience'),
        ),
    ]
